# Generated by Django 6.0 on 2026-01-30 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_userprofile_role_userprofile_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('food', 'Food Order'), ('cab', 'Cab Booking'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='api.reservation')),
            ],
        ),
    ]
