# Generated by Django 5.2.11 on 2026-02-17 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_food_is_available_room_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
