# Generated by Django 5.2.11 on 2026-02-25 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_room_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled'), ('Checked-In', 'Checked-In'), ('Checked-Out', 'Checked-Out')], default='Pending', max_length=16),
        ),
    ]
