# Generated by Django 5.2.11 on 2026-03-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0021_room_number_of_rooms"),
    ]

    operations = [
        migrations.AddField(
            model_name="roomprice",
            name="is_closed",
            field=models.BooleanField(
                default=False,
                help_text="If true, booking is closed for this room/date",
            ),
        ),
    ]
